name: HazeStore
version: '${version}'
main: com.kala.hazestore.Hazestore
api-version: '1.19'
softdepend: [MMOItems, CoinsEngine, PlaceholderAPI]
commands:
  hs:
    description: "Main command for HazeStore"
    permission: "hs.open"
    usage: "/hs [open|admin]"
permissions:
  hs.open:
    description: "Allows opening the HazeStore GUI"
    default: true
  hs.vip:
    description: "Allows seeing and buying VIP items"
    default: op
  hs.admin:
    description: "Allows the editor, reload, force rotation and bypassing hidden/VIP masking"
    default: op
